services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: go-microservice
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: go-microservice
    ports:
      - '5432:5432'
    volumes:
      - db_product_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: go-microservice
      DB_PASSWORD: secret
      DB_NAME: go-microservice
      DB_HOST: database
      DB_PORT: 5432
    ports:
      - '8080:8080'
    depends_on:
      - database

volumes:
  db_product_data:
