services:
  service:
    image: service
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: .
        target: /app/
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/postgres
    networks:
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped
  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  backend:
